CREATE TABLE DRIVER
(
    ID      SERIAL PRIMARY KEY,
    NAME    VARCHAR(75),
    SURNAME VARCHAR(75),
    EMAIL   VARCHAR(100),
    ADDRESS VARCHAR(20),
    LICENCE VARCHAR(20),
    PHONE   NUMERIC
);

CREATE
    INDEX IDX_DRIVER_FBI ON DRIVER (ID);

INSERT INTO DRIVER (ID, NAME, SURNAME ,ADDRESS, EMAIL, PHONE, LICENCE)
VALUES (2 , 'LEVENT' , 'CAMKIRIK' , 'ARD' , 'LEVENT31@OUTLOOK.COM' , 97836363 , '1213aasqweq123');
COMMIT;